### ISSUE TITLE
if mongo is stopped in replicaset the ALARM is not triggered (in log)

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/perseo-fe#230]
Tested in INT environment. If mongo (replicaset) are stopped the ALARM is not triggered (in log). Also tested with a only one node.

#### First test
Perseo uses three mongo nodes in replicaset, and starts successfully, and after all mongo nodes are stopped:
```
time=2017-01-05T11:17:21.481Z | lvl=FATAL | corr=n/a | trans=n/a | op=perseo | comp=perseo-fe | msg=uncaughtException: Cannot read property 'hasListCollectionsCommand' of undefined TypeError: Cannot read property 'hasListCollectionsCommand' of undefined,    at Db.listCollections (/opt/perseo/node_modules/mongodb/lib/mongodb/db.js:425:49),    at Db.collection (/opt/perseo/node_modules/mongodb/lib/mongodb/db.js:536:8),    at fn (/opt/perseo/node_modules/async/lib/async.js:638:34),    at Object._onImmediate (/opt/perseo/node_modules/async/lib/async.js:554:34),    at processImmediate [as _immediateCallback] (timers.js:363:15)
```

#### Second test
Perseo uses a only mongo node and starts successfully, and after the mongo node is stopped:
```
time=2017-01-05T11:43:48.109Z | lvl=FATAL | corr=n/a | trans=n/a | op=perseo | comp=perseo-fe | msg=uncaughtException: Cannot read property 'hasListCollectionsCommand' of undefined TypeError: Cannot read property 'hasListCollectionsCommand' of undefined,    at Db.listCollections (/opt/perseo/node_modules/mongodb/lib/mongodb/db.js:425:49),    at Db.collection (/opt/perseo/node_modules/mongodb/lib/mongodb/db.js:536:8),    at fn (/opt/perseo/node_modules/async/lib/async.js:638:34),    at Object._onImmediate (/opt/perseo/node_modules/async/lib/async.js:554:34),    at processImmediate [as _immediateCallback] (timers.js:363:15)
```

#### Third test
Started the perseo successfully and modified the interval to rule refresh to a long time value. (i.e: interval: 60e3*60*24) and after, the mongo is stopped.

Then nothing is logged, seem as if the ping to verify conectivity with database is not executed

**Comment by iariasleon** [comment]
Tests performed to generate the alarms if the mongo falls and the subsequent shutdown of the same (alarms), once the connection of a mongo has been correctly restored. See the report in https://gist.github.com/iariasleon/20b3689084c1a214679d005dc49d0226
