### ISSUE TITLE
Error message is nor clear if missing any fields in config.js

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/perseo-fe#233]
Error message is nor clear if missing any fields in config.js
Ex: 

If the `metricsPath: '/admin/metrics'` field is missing, in the log this stored:
```
time=2017-01-19T09:27:32.524Z | lvl=INFO | corr=n/a | trans=n/a | op=start | comp=perseo-fe | msg=starting perseo
time=2017-01-19T09:27:32.569Z | lvl=FATAL | corr=n/a | trans=n/a | op=perseo | comp=perseo-fe | msg=uncaughtException: Cannot read property 'length' of undefined TypeError: Cannot read property 'length' of undefined,    at pathtoRegexp (/opt/perseo/node_modules/express/node_modules/path-to-regexp/index.js:63:48),    at new Layer (/opt/perseo/node_modules/express/lib/router/layer.js:45:17),    at Function.route (/opt/perseo/node_modules/express/lib/router/index.js:494:15),    at EventEmitter.app.(anonymous function) [as get] (/opt/perseo/node_modules/express/lib/application.js:480:30),    at Object.AddTo (/opt/perseo/lib/routes/metricsController.js:38:9),    at /opt/perseo/lib/perseo.js:92:23,    at b (domain.js:184:18),    at Domain.run (domain.js:124:23),    at Object.start (/opt/perseo/lib/perseo.js:65:7),    at Object.<anonymous> (/opt/perseo/bin/perseo:122:5)
```

**Comment by AlvaroVega** [comment]
It is expected that config has fully config.endpoint fields...
```
config.endpoint = {
    host: 'localhost',
    port: 9090,
    rulesPath: '/rules',
    actionsPath: '/actions/do',
    noticesPath: '/notices',
    vrPath: '/m2m/vrules',
    checkPath: '/check',
    versionPath: '/version',
    logPath: '/admin/log',
    metricsPath: '/admin/metrics'
};
```
