### ISSUE TITLE
Error: Cannot find module 'smpp' when start this server

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/perseo-fe#249]
When we try to start this server (node/perseo), then fails with following error:
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'smpp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/perseo-fe/lib/models/smppAction.js:28:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

It seems necessary to add a reference to smpp in the file npm-shrinkwrap.json

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/perseo-fe/pull/250
