### ISSUE TITLE
Read the Docs buildings are falling

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/perseo-fe#598]
RTD building is failing giving the following error: `ModuleNotFoundError: No module named 'pymdownx'`. 

Checking the file `mkdocs_requirements.txt`, it seems is provided:
https://github.com/telefonicaid/perseo-fe/blob/dca8830ca73cd886ae6c347bf306a50202346267/mkdocs_requirements.txt#L2

Also it appears in `mkdocs.yml` file:
https://github.com/telefonicaid/perseo-fe/blob/dca8830ca73cd886ae6c347bf306a50202346267/mkdocs.yml#L27-L38

Log (also available on [RTD site](https://readthedocs.org/projects/fiware-perseo-fe/builds/15232887/)): 

```
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/checkouts/latest/_build/html 
ERROR   -  Error building page index.md 
Traceback (most recent call last):
  File "/home/docs/.pyenv/versions/3.6.12/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/docs/.pyenv/versions/3.6.12/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/envs/latest/lib/python3.6/site-packages/mkdocs/__main__.py", line 194, in <module>
    cli()
  File "/home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/envs/latest/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/envs/latest/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/envs/latest/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/envs/latest/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/envs/latest/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/envs/latest/lib/python3.6/site-packages/mkdocs/__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/envs/latest/lib/python3.6/site-packages/mkdocs/commands/build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/envs/latest/lib/python3.6/site-packages/mkdocs/commands/build.py", line 242, in build_pages
    _build_page(page, config, site_navigation, env)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/envs/latest/lib/python3.6/site-packages/mkdocs/commands/build.py", line 137, in _build_page
    page.render(config, site_navigation)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/envs/latest/lib/python3.6/site-packages/mkdocs/nav.py", line 293, in render
    extension_configs=config['mdx_configs'] or {}
  File "/home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/envs/latest/lib/python3.6/site-packages/markdown/core.py", line 97, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/envs/latest/lib/python3.6/site-packages/markdown/core.py", line 123, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/envs/latest/lib/python3.6/site-packages/markdown/core.py", line 162, in build_extension
    module = importlib.import_module(ext_name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fiware-perseo-fe/envs/latest/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pymdownx'
```

CC: @jason-fox @cblanco

**Comment by jason-fox** [comment]
Not sure if it will fix it, but there are two things you could try.

1.  Move and rename the `mkdocs_requirements.txt` → `docs/requirements.txt` - the `readthedocs.yml` expects it in a different place
2.  Comment out the failing extensions if they still cannot be loaded by updating the `mkdocs.yml`

You can see what I mean here on [a branch of my fork]( https://github.com/jason-fox/perseo-fe/commit/adc17f9d43fdc9d3e2c66e626c3ae6e433c61556)

**Comment by mapedraza** [comment]
After merging https://github.com/telefonicaid/perseo-fe/pull/599, it works propperly. 

This issue can be closed
